// Generated by: rad aspire convert
// Source: ./aspire-manifest.json
// Date: 2026-02-19T00:00:00Z

extension containers
extension radius

@description('The ID of your Radius Environment. Set automatically by the rad CLI.')
param environment string
@description('The name of the Radius Application.')
param applicationName string = 'aspire-app'

resource app 'Radius.Core/applications@2025-08-01-preview' = {
  name: applicationName
  properties: {
    environment: environment
  }
}

// WARNING: app (container.v1) has a build configuration (context: 'app').
// Build and push the container image before deploying. For example:
//   docker build -t <registry>/app:latest app
//   docker push <registry>/app:latest
// Then update the 'image' property below with the pushed image reference.
resource appContainer 'Radius.Compute/containers@2025-08-01-preview' = {
  name: 'app'
  properties: {
    application: app.id
    environment: environment
    container: {
      image: '<YOUR_REGISTRY>/app:latest'
      command: [
        'main:app'
        '--host'
        '0.0.0.0'
        '--port'
        '8000'
      ]
      ports: {
        http: {
          containerPort: 8000
          protocol: 'TCP'
        }
      }
      env: {
        CACHE_HOST: cache.id
        CACHE_PASSWORD: cache_password
        CACHE_PORT: cache.id
        CACHE_URI: 'redis://:${cache_password_uri_encoded.id}@${cache.id}:${cache.id}'
        ConnectionStrings__cache: cache.id
        OTEL_LOGS_EXPORTER: 'otlp'
        OTEL_METRICS_EXPORTER: 'otlp'
        OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: 'true'
        OTEL_TRACES_EXPORTER: 'otlp'
        PORT: '8000'
      }
    }
    connections: {
      cache: {
        source: cache.id
      }
    }
  }
}

resource cache 'Radius.Compute/containers@2025-08-01-preview' = {
  name: 'cache'
  properties: {
    application: app.id
    environment: environment
    container: {
      image: 'docker.io/library/redis:8.2'
      command: [
        '/bin/sh'
        '-c'
        'redis-server --requirepass $REDIS_PASSWORD'
      ]
      ports: {
        tcp: {
          containerPort: 6379
          protocol: 'TCP'
        }
      }
      env: {
        REDIS_PASSWORD: cache_password
      }
    }
  }
}

// WARNING: frontend (container.v1) has a build configuration (context: 'frontend').
// Build and push the container image before deploying. For example:
//   docker build -t <registry>/frontend:latest frontend
//   docker push <registry>/frontend:latest
// Then update the 'image' property below with the pushed image reference.
resource frontend 'Radius.Compute/containers@2025-08-01-preview' = {
  name: 'frontend'
  properties: {
    application: app.id
    environment: environment
    container: {
      image: '<YOUR_REGISTRY>/frontend:latest'
      ports: {
        http: {
          containerPort: 8001
          protocol: 'TCP'
        }
      }
      env: {
        APP_HTTP: appContainer.id
        NODE_ENV: 'production'
        PORT: '8001'
        services__app__http__0: appContainer.id
      }
    }
    connections: {
      app: {
        source: appContainer.id
      }
    }
  }
}

resource appContainerGateway 'Radius.Compute/routes@2025-08-01-preview' = {
  name: 'app-gateway'
  properties: {
    application: app.id
    environment: environment
    routes: [
      {
        path: '/'
        destination: appContainer.id
        port: 8000
      }
    ]
  }
}

// Unsupported: cache-password-uri-encoded (annotated.string) — manual configuration required
