/*
Copyright 2026 The Radius Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package generate

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/radius-project/radius/pkg/cli/clierrors"
	"github.com/radius-project/radius/pkg/cli/framework"
	"github.com/radius-project/radius/pkg/cli/output"
	"github.com/spf13/cobra"
)

// NewCommand creates a new instance of the `rad bicep generate` command.
func NewCommand(factory framework.Factory) (*cobra.Command, framework.Runner) {
	runner := NewRunner(factory)

	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate a Radius app.bicep from Aspire artifacts",
		Long: `Generate a Radius-deployable app.bicep file from Aspire-generated infrastructure artifacts.

This command reads Bicep files generated by 'azd infra synth' for a .NET Aspire application
and produces a Radius-compatible app.bicep file along with a mapping report documenting the conversion.`,
		Example: `
# Basic usage — convert azd infra synth output in ./infra
rad bicep generate --from-aspire ./infra

# Specify output paths
rad bicep generate --from-aspire ./infra --output ./deploy/app.bicep --report ./deploy/mapping-report.md

# Override application name
rad bicep generate --from-aspire ./infra --app-name my-app

# Quiet mode (suppress console report)
rad bicep generate --from-aspire ./infra --quiet

# Deterministic mode for CI (fixed timestamps)
rad bicep generate --from-aspire ./infra --deterministic
`,
		Args: cobra.NoArgs,
		RunE: framework.RunCommand(runner),
	}

	cmd.Flags().String("from-aspire", "", "Path to the directory containing azd infra synth output Bicep files (required)")
	_ = cmd.MarkFlagRequired("from-aspire")

	cmd.Flags().StringP("output", "o", "./app.bicep", "Path for the generated app.bicep output file")
	cmd.Flags().String("app-name", "", "Name for the Radius application resource (derived from Aspire project if not set)")
	cmd.Flags().String("report", "./mapping-report.md", "Path for the companion mapping report Markdown file")
	cmd.Flags().BoolP("quiet", "q", false, "Suppress console mapping report output (file still generated)")
	cmd.Flags().Bool("deterministic", false, "Replace timestamps with a fixed sentinel value for idempotency verification in CI")

	return cmd, runner
}

// Runner is the runner implementation for the `rad bicep generate` command.
type Runner struct {
	Output output.Interface

	FromAspirePath string
	OutputPath     string
	AppName        string
	ReportPath     string
	Quiet          bool
	Deterministic  bool
}

// NewRunner creates a new instance of the `rad bicep generate` runner.
func NewRunner(factory framework.Factory) *Runner {
	return &Runner{
		Output: factory.GetOutput(),
	}
}

// Validate validates the inputs of the rad bicep generate command.
func (r *Runner) Validate(cmd *cobra.Command, args []string) error {
	fromAspire, err := cmd.Flags().GetString("from-aspire")
	if err != nil {
		return err
	}

	if fromAspire == "" {
		return clierrors.Message("--from-aspire flag is required. Provide the path to the azd infra synth output directory.")
	}

	r.FromAspirePath = fromAspire

	r.OutputPath, err = cmd.Flags().GetString("output")
	if err != nil {
		return err
	}

	r.AppName, err = cmd.Flags().GetString("app-name")
	if err != nil {
		return err
	}

	r.ReportPath, err = cmd.Flags().GetString("report")
	if err != nil {
		return err
	}

	r.Quiet, err = cmd.Flags().GetBool("quiet")
	if err != nil {
		return err
	}

	r.Deterministic, err = cmd.Flags().GetBool("deterministic")
	if err != nil {
		return err
	}

	return nil
}

// Run runs the rad bicep generate command.
func (r *Runner) Run(ctx context.Context) error {
	// Step 1: Discover Bicep files
	r.Output.LogInfo("Converting Aspire artifacts from: %s", r.FromAspirePath)

	filePaths, err := ScanDirectory(r.FromAspirePath)
	if err != nil {
		return clierrors.Message("Failed to scan directory: %s", err)
	}

	// Step 2: Parse each discovered file
	var parsedFiles []BicepFile
	for _, fp := range filePaths {
		bf, err := ParseFile(fp)
		if err != nil {
			return clierrors.Message("Failed to parse '%s': %s", fp, err)
		}
		parsedFiles = append(parsedFiles, bf)
	}

	// Step 3: Map to Radius model
	absSourceDir, err := filepath.Abs(r.FromAspirePath)
	if err != nil {
		absSourceDir = r.FromAspirePath
	}

	app, err := MapToRadius(parsedFiles, r.AppName, absSourceDir)
	if err != nil {
		return clierrors.Message("Failed to map Aspire resources to Radius model: %s", err)
	}

	// Print discovery summary
	serviceNames := make([]string, 0, len(app.Containers))
	for _, c := range app.Containers {
		serviceNames = append(serviceNames, c.Name)
	}
	r.Output.LogInfo("  Found %d services: %s", len(app.Containers), strings.Join(serviceNames, ", "))

	depDescs := make([]string, 0, len(app.Dependencies))
	for _, d := range app.Dependencies {
		if d.IsPlaceholder {
			depDescs = append(depDescs, fmt.Sprintf("%s (unsupported)", d.Name))
		} else {
			depDescs = append(depDescs, fmt.Sprintf("%s (Redis)", d.Name))
		}
	}
	if len(depDescs) > 0 {
		r.Output.LogInfo("  Found %d dependency: %s", len(app.Dependencies), strings.Join(depDescs, ", "))
	}

	// Step 4: Generate app.bicep output
	r.Output.LogInfo("")
	r.Output.LogInfo("Generating app.bicep...")

	timestamp := time.Now().UTC().Format(time.RFC3339)
	if r.Deterministic {
		timestamp = "DETERMINISTIC"
	}

	bicepOutput, err := GenerateAppBicep(app, r.FromAspirePath, timestamp)
	if err != nil {
		return clierrors.Message("Failed to generate app.bicep: %s", err)
	}

	// Step 5: Write output file
	outputDir := filepath.Dir(r.OutputPath)
	if outputDir != "" && outputDir != "." {
		if err := os.MkdirAll(outputDir, 0755); err != nil {
			return clierrors.Message("Failed to create output directory '%s': %s", outputDir, err)
		}
	}

	if err := os.WriteFile(r.OutputPath, []byte(bicepOutput), 0644); err != nil {
		return clierrors.Message("Failed to write output file '%s': %s", r.OutputPath, err)
	}

	// Print generation summary
	r.Output.LogInfo("  ✓ Application: %s", app.Name)
	for _, c := range app.Containers {
		r.Output.LogInfo("  ✓ Container: %s (image param: %s)", c.Name, c.ImageParam)
	}
	for _, d := range app.Dependencies {
		if d.IsPlaceholder {
			r.Output.LogInfo("  ⚠ Dependency: %s (placeholder — %s)", d.Name, d.PlaceholderComment)
		} else {
			r.Output.LogInfo("  ✓ Dependency: %s (%s, Recipe-backed)", d.Name, d.Type)
		}
	}
	for _, c := range app.Containers {
		for _, conn := range c.Connections {
			r.Output.LogInfo("  ✓ Connection: %s → %s", c.Name, conn.TargetResourceName)
		}
	}

	r.Output.LogInfo("")
	r.Output.LogInfo("Output written to: %s", r.OutputPath)

	return nil
}
